image: docker:latest

services:
  - docker:dind

build:
  stage: deploy
  before_script:
    - export DYNAMIC_ENV_VAR=STAGING
  script:
    - echo setting up env $DYNAMIC_ENV_VAR
    - docker image prune -f
    - docker-compose -f docker-compose.yml build --no-cache
    - docker-compose -f docker-compose.yml up -d
